version: '2.1'

services:
  statistics-py:
    image: statistics-py
    build: .
    ports:
      - 3000:3000
    depends_on:
      - statistics-db
  statistics-db:
    image: postgres
    ports:
      - "5432:5432"