version: '2'

services:
  statistics-ms:
    build: .
    command: gunicorn statistics_ms.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 3008:8000
    environment:
      - SECRET_KEY=statistics
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - statistics-db
  statistics-db:
    image: postgres:10.5-alpine