version: '2'

services:
  statistics_db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  statistics_ms:
    build: .
    command: python3 manage.py runserver 0.0.0.0:3004
    expose:
      - "3004"
    ports:
      - "3004:3004"
    volumes:
        - .:/code
    links:
    - statistics_db

volumes:
  postgres_data: