version: '2'
services:
  web:
    build: .
    links:
    - db
    ports:
    - "3004:3004"

  db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "statisticsadmin"
      POSTGRES_PASSWORD: "arqsoftun"