version: '2'

services:
  statistics-ms:
    build: .
    command: ["gunicorn", "statistics_ms.wsgi:application", "--bind", "0.0.0.0:8000"]
    ports:
      - 3007:8000
    environment:
      - SECRET_KEY=statistics
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=statistics-db
      - SQL_PORT=5432
    depends_on:
      - statistics-db
  statistics-db:
    image: postgres
